// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ClerkProvider } from '@clerk/nextjs'
// import { dark, neobrutalism, shadesOfPurple } from '@clerk/themes'

// import HeaderVisibility from "./(Pages)/(HomePage)/_components/HeaderVisibility";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider appearance={{baseTheme: shadesOfPurple}}>
//     <html lang="en" className="bg-[#BBFBFF]">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable}  antialiased `}
//       >
//         <div>
//           <HeaderVisibility />
//         </div>
//         <div>
//           {children}
//         </div>
        
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }



import {  Poppins, Inter, Alice  } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { shadesOfPurple } from "@clerk/themes";

import HeaderVisibility from "./(Pages)/(HomePage)/_components/HeaderVisibility";
import FooterVisibility from "./(Pages)/(HomePage)/_components/FooterVisibility";

// Existing fonts


// New fonts
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose weights you need
});
const alice = Alice({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: "--font-alice" 
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: shadesOfPurple }}>
      <html lang="en" className="bg-[#F5F5F5]">
        <body
          className={` ${poppins.variable} ${inter.variable} ${alice.variable} antialiased`}
        >
          <div>
            <HeaderVisibility />
          </div>
          <div>{children}</div>
          <div>
            <FooterVisibility />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}

